"""
Risk-score model: aggregates incidents into zone-hour buckets, trains an
XGBoost regressor on a severity-weighted risk_score (0-1), and exposes
predict_risk() / predict_risk_fallback() for inference.

Inputs : zones.json, events.json, incidents.csv  (generated by generate_data.py)
Outputs: model.json, zone_base_rate.json
Run    : python risk_model.py
Deps   : numpy, pandas, xgboost, scikit-learn
"""

import json, pathlib
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.metrics import mean_squared_error, mean_absolute_error
import xgboost as xgb

# ── paths (resolve relative to THIS file, not cwd) ──────────────────────────
ROOT = pathlib.Path(__file__).parent
MODEL_PATH = ROOT / "model.json"
ZBR_PATH   = ROOT / "zone_base_rate.json"

# Ordinal-encode weather: clear=0, rain=1, storm=2
WEATHER_MAP = {"clear": 0, "rain": 1, "storm": 2}

FEATURES = [
    "hour_of_day", "day_of_week", "is_weekend",
    "weather_enc", "is_event_day", "expected_crowd_size", "zone_base_rate",
]
TARGET = "risk_score"


# ── TRAINING FUNCTION (only runs when script is executed directly) ───────────
def train_model():
    """Load data, engineer features, train XGBoost, save artifacts."""

    # ── 1. LOAD & AGGREGATE ──────────────────────────────────────────────
    df = pd.read_csv(ROOT / "incidents.csv", parse_dates=["timestamp"])
    events = json.loads((ROOT / "events.json").read_text())

    # Build event lookup: (date_str, zone_id) -> max expected_crowd_size
    event_lookup: dict[tuple[str, int], int] = {}
    for e in events:
        key = (e["date"], e["zone_id"])
        event_lookup[key] = max(event_lookup.get(key, 0), e["expected_crowd_size"])

    # Derive date / hour columns
    df["date"]        = df["timestamp"].dt.date
    df["hour"]        = df["timestamp"].dt.hour
    df["date_str"]    = df["timestamp"].dt.strftime("%Y-%m-%d")

    # Aggregate into zone-hour buckets: severity-weighted incident score
    agg = (
        df.groupby(["zone_id", "date", "hour"])
          .agg(raw_score=("severity", "sum"),
               date_str=("date_str", "first"),
               weather_condition=("weather_condition", "first"),
               is_event_day=("is_event_day", "first"))
          .reset_index()
    )

    # Min-max normalize raw_score -> risk_score (0-1)
    rmin, rmax = agg["raw_score"].min(), agg["raw_score"].max()
    agg["risk_score"] = (agg["raw_score"] - rmin) / (rmax - rmin)

    # ── 2. FEATURE ENGINEERING ───────────────────────────────────────────
    agg["date_dt"]       = pd.to_datetime(agg["date"])
    agg["hour_of_day"]   = agg["hour"]
    agg["day_of_week"]   = agg["date_dt"].dt.dayofweek        # 0=Mon..6=Sun
    agg["is_weekend"]    = (agg["day_of_week"] >= 5).astype(int)

    agg["weather_enc"] = agg["weather_condition"].map(WEATHER_MAP)

    agg["expected_crowd_size"] = agg.apply(
        lambda r: event_lookup.get((r["date_str"], r["zone_id"]), 0), axis=1
    )
    agg["is_event_day"] = agg["is_event_day"].astype(int)

    # ── 3. TEMPORAL TRAIN / TEST SPLIT (75 / 25 by date) ─────────────────
    all_dates = sorted(agg["date_dt"].unique())
    split_idx = int(len(all_dates) * 0.75)
    train_dates = set(all_dates[:split_idx])

    train_mask = agg["date_dt"].isin(train_dates)
    train_df   = agg[train_mask].copy()

    # zone_base_rate — mean risk_score per zone, ONLY from training data
    zone_base_rate: dict[int, float] = (
        train_df.groupby("zone_id")["risk_score"].mean().to_dict()
    )
    agg["zone_base_rate"] = agg["zone_id"].map(zone_base_rate).fillna(0.0)
    train_df = agg[train_mask].copy()
    test_df  = agg[~train_mask].copy()

    X_train, y_train = train_df[FEATURES], train_df[TARGET]
    X_test,  y_test  = test_df[FEATURES],  test_df[TARGET]

    print(f"Train rows: {len(X_train)}  |  Test rows: {len(X_test)}")
    print(f"Date range  train: {min(train_dates).date()} .. {max(train_dates).date()}")
    print(f"Date range  test : {min(all_dates[split_idx:]).date()} .. {max(all_dates[split_idx:]).date()}")

    # ── 4. TRAIN XGBOOST ─────────────────────────────────────────────────
    model = xgb.XGBRegressor(
        n_estimators=200, max_depth=5, learning_rate=0.1,
        subsample=0.8, colsample_bytree=0.8,
        random_state=42, verbosity=0,
    )
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae  = mean_absolute_error(y_test, y_pred)
    print(f"\nTest RMSE: {rmse:.4f}  |  Test MAE: {mae:.4f}")

    # Feature importances (gain-based, sorted descending)
    imp = dict(zip(FEATURES, model.feature_importances_))
    imp_sorted = sorted(imp.items(), key=lambda x: x[1], reverse=True)
    print("\nFeature importances:")
    for feat, score in imp_sorted:
        print(f"  {feat:25s} {score:.4f}")

    # ── 5. SAVE MODEL & ZONE BASE RATE ───────────────────────────────────
    model.save_model(str(MODEL_PATH))
    ZBR_PATH.write_text(json.dumps(
        {str(k): round(v, 6) for k, v in zone_base_rate.items()}, indent=2))
    print(f"\nSaved model  -> {MODEL_PATH}")
    print(f"Saved lookup -> {ZBR_PATH}")


# ── 6. INFERENCE FUNCTIONS (importable without triggering training) ──────────
_cached_model = None
_cached_zbr   = None

def _load_artifacts():
    global _cached_model, _cached_zbr
    if _cached_model is None:
        _cached_model = xgb.XGBRegressor()
        _cached_model.load_model(str(MODEL_PATH))
    if _cached_zbr is None:
        raw = json.loads(ZBR_PATH.read_text())
        _cached_zbr = {int(k): v for k, v in raw.items()}
    return _cached_model, _cached_zbr


def predict_risk(zone_id: int, timestamp: datetime, weather_condition: str,
                 is_event_day: bool, expected_crowd_size: int = 0) -> float:
    """Return a 0-1 risk score for a single zone-hour using the trained XGBoost model."""
    mdl, zbr = _load_artifacts()
    row = pd.DataFrame([{
        "hour_of_day":          timestamp.hour,
        "day_of_week":          timestamp.weekday(),
        "is_weekend":           int(timestamp.weekday() >= 5),
        "weather_enc":          WEATHER_MAP[weather_condition],
        "is_event_day":         int(is_event_day),
        "expected_crowd_size":  expected_crowd_size,
        "zone_base_rate":       zbr.get(zone_id, 0.0),
    }])
    pred = float(mdl.predict(row)[0])
    return max(0.0, min(1.0, pred))   # clamp to [0, 1]


# ── 7. FALLBACK (NO ML) ─────────────────────────────────────────────────────
def predict_risk_fallback(zone_id: int, weather_condition: str,
                          is_event_day: bool,
                          expected_crowd_size: int = 0) -> float:
    """Transparent weighted-sum fallback — no model needed."""
    _, zbr = _load_artifacts()
    base = zbr.get(zone_id, 0.05)
    # Weather weight: clear +0, rain +0.08, storm +0.18
    wx = {"clear": 0.0, "rain": 0.08, "storm": 0.18}[weather_condition]
    # Event proximity weight: scaled 0 -> 0.25 by crowd size
    ev = 0.0
    if is_event_day and expected_crowd_size > 0:
        ev = 0.10 + 0.15 * min(expected_crowd_size, 15000) / 15000
    score = base + wx + ev
    return max(0.0, min(1.0, score))


# ── 8. EXAMPLE PREDICTIONS ──────────────────────────────────────────────────
if __name__ == "__main__":
    # Train the model first
    train_model()

    examples = [
        # (zone_id, timestamp,                          weather,  event, crowd)
        (0, datetime(2026, 7, 20, 23, 0), "rain",  False, 0),      # Downtown, late night, rain
        (4, datetime(2026, 6, 14, 10, 0), "clear", True,  8000),   # Northgate, morning, event
        (6, datetime(2026, 5, 30, 2,  0), "storm", False, 0),      # Industrial, 2 AM, storm
    ]
    print("\n" + "=" * 60)
    print("  Example predictions (XGBoost / Fallback)")
    print("=" * 60)
    for zid, ts, wx, ev, crowd in examples:
        ml = predict_risk(zid, ts, wx, ev, crowd)
        fb = predict_risk_fallback(zid, wx, ev, crowd)
        tag = f"zone={zid}  {ts:%a %H:%M}  wx={wx:5s}  event={ev}"
        print(f"  {tag:50s}  ML={ml:.3f}  Fallback={fb:.3f}")
